[package]
name = "hir"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2021"
repository= "https://github.com/pascalkuthe/OpenVAF"
description = "A compiler frontend for VerilogA aimed predominantly at compact modelling"
license="GPL-3.0"
readme="../README.md"

[badges]
maintenance = { status = "actively-developed" }

[lib]
doctest = false

[dependencies]

basedb = {version = "0.0.0", path = "../basedb" }
# syntax = {version = "0.0.0", path = "../syntax"}
stdx = {version = "0.0.0", path = "../../lib/stdx" }

hir_def = {version = "0.0.0", path = "../hir_def" }
hir_ty = {version = "0.0.0", path = "../hir_ty" }
syntax = {version = "0.0.0", path = "../syntax"}
indexmap = "2.0"

salsa = "0.17.0-pre.2"

typed-index-collections = "3.1"

anyhow = "1"
smol_str = { version = "0.2", default-features=false }
parking_lot = "0.12"

[dev-dependencies]
expect-test = "1.4"
mini_harness = { version = "0.0.1", path = "../../lib/mini_harness" }

[[test]]
name = "data_tests"
harness = false

