[package]
name = "osdi"
version = "0.0.0"
authors = ["DSPOM"]
edition = "2021"
license = "GPL-3.0"

[lib]
doctest = false

[dependencies]

stdx = { version = "0.0.0", path = "../../lib/stdx" }
typed_indexmap = {version = "0.0.0", path = "../../lib/typed_indexmap"}
paths = {version = "0.0", path = "../../lib/paths"}

hir_lower = {version ="0.0.0", path ="../hir_lower"}
hir = { version = "0.0.0", path = "../hir" }
sim_back = { version = "0.0.0", path = "../sim_back" }

mir = { version = "0.0.0", path = "../mir" }
mir_llvm = { version = "0.0.0", path = "../mir_llvm" }

#llvm = { version = "0.0.0", path = "../llvm" }
llvm-sys = "181.1.1"
target = { version = "0.0.0", path = "../target"}

typed-index-collections = "3.1"
ahash = "0.8"
lasso = {version = "0.7", features = ["ahash"]}

salsa = "0.17.0-pre.2"
indexmap = "2.0"
smol_str = {version = "0.2", default-features=false}

base_n = {version = "1", path="../../lib/base_n"}
rayon-core = "1"

camino = "1.1.4"
log = "0.4.19"

[build-dependencies]

xshell = "0.2.3"
stdx = {version ="0.0.0", path ="../../lib/stdx"}
target = { version = "0.0.0", path = "../target" }

[dev-dependencies]

expect-test = "1.4"
mir_interpret = {version = "0.0.0", path = "../mir_interpret" }
float-cmp =  "0.9"
mini_harness = { version = "0.0.1", path = "../../lib/mini_harness" }

[[test]]
name = "data_tests"
harness = false
