[package]
name = "openvaf"
version = "0.1.2"
authors = ["DSPOM"]
edition = "2021"
license = "GPL-3.0"

[lib]
doctest = false

[dependencies]

tokens = { version = "0.0.0", path = "../tokens" }
basedb = { version = "0.0.0", path = "../basedb" }
sim_back = { version = "0.0.0", path = "../sim_back" }
osdi = { version = "0.0.0", path = "../osdi" }

#llvm = { version = "0.0.0", path = "../llvm" }
llvm-sys = "181.1.1"
mir_llvm = { version = "0.0.0", path = "../mir_llvm" }
hir = { version = "0.0.0", path = "../hir" }
target = { version = "0.0.0", path = "../target" }
linker = { version = "0.0.0", path = "../linker" }

base_n = { version = "1", path = "../../lib/base_n" }
paths = { version = "0.0", path = "../../lib/paths" }

md5 = "0.7"

anyhow = "1"
termcolor = "1.2"
camino = "1.1.4"

[dev-dependencies]
libloading = "0.8"
libc = "0.2"
float-cmp =  "0.9"
mini_harness = { version = "0.0.1", path = "../../lib/mini_harness" }
stdx = { version = "0.0.0", path = "../../lib/stdx" }
expect-test = "1.4"
bitflags = "2.4.1"
indexmap = "2.0"

[[test]]
name = "integration"
harness = false
