[package]
name = "verilogae"
version = "1.0.0"
authors = ["DSPOM"]
edition = "2021"
license = "GPL-3.0"

[lib]
doctest = false
crate-type = ["lib", "cdylib"]
name = "verilogae"

[dependencies]

syntax = { version = "0.0.0", path = "../../openvaf/syntax" }
basedb = { version = "0.0.0", path = "../../openvaf/basedb" }
hir_lower = { version = "0.0.0", path = "../../openvaf/hir_lower" }
hir = { version = "0.0.0", path = "../../openvaf/hir" }

mir = { version = "0.0.0", path = "../../openvaf/mir" }
mir_llvm = { version = "0.0.0", path = "../../openvaf/mir_llvm" }
mir_opt = { version = "0.0.0", path = "../../openvaf/mir_opt" }
mir_autodiff = { version = "0.0.0", path = "../../openvaf/mir_autodiff" }

#llvm = { version = "0.0.0", path = "../../openvaf/llvm" }
llvm-sys = "181.1.1"
target = { version = "0.0.0", path = "../../openvaf/target" }
linker = { version = "0.0.0", path = "../../openvaf/linker" }

stdx = { version = "0.0.0", path = "../../lib/stdx" }
typed_indexmap = { version = "0.0.0", path = "../../lib/typed_indexmap" }
bitset = { version = "0.0.0", path = "../../lib/bitset" }
base_n = { version = "1", path = "../../lib/base_n" }
paths = { version = "0.0", path = "../../lib/paths" }

lasso = { version = "0.7", features = ["ahash"] }
indexmap = "2.0"
md5 = "0.7"
directories-next = "2"
libloading = "0.8"

rayon-core = "1"

smol_str = { version = "0.2", default-features = false }
typed-index-collections = "3"
ahash = "0.8"

anyhow = "1"
termcolor = "1.2"

salsa = "0.17.0-pre.2"
camino = "1.1.4"
